### ISSUE TITLE
Make API port configurable

### ISSUE THREAD

**Issue by stvvt** [martinmarinov150402/RestAPI#1]
API port (3000) is now hardcoded.

https://github.com/martinmarinov150402/RestAPI/blob/7a756d278645a2e538a12a03c1e6e6f82c0c7687/src/main.ts#L6

Please use the value `API_PORT` environment variable instead of the hardcoded value. If not set, the port should default 3000.

**Comment by martinmarinov150402** [comment]
Now you can change it using config files or environment variable it's your choice.
